module:
    _target_: train_longitudinal.LongitudinalTrainingModule
    num_inter_by_epoch: 4
max_steps: 15000
accumulate_grad_batches: 4
sim_loss: "mi"
lambda_reg: 0.1
lambda_sim: 1.0
lambda_seg: 5.0
lambda_mag: 0.1
lambda_grad: 0.01
lambda_inv: 0.1
learning_rate: 0.001
batch_size: 1
checkpoint: ""
penalize: "v"
save_dir: 'longitudinal'
mode: "longitudinal"
load: ""
temporal_load: ""