_target_: modules.pairwise_registration.PairwiseRegistrationModuleVelocity
int_steps: 7
model:
  _target_: monai.networks.nets.AttentionUnet
  dropout: 0.1
  spatial_dims: 3
  in_channels: 2
  out_channels: 3
  channels: [8, 16, 32, 64]
  strides: [2, 2, 2]