defaults:
  - data: dhcpatlas
  - pairwise_model: default
  - longitudinal_model: mlp
  - train: longitudinal/dhcp_mlp

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: version_${hydra.job.num}
  job:
    name: longitudinal
