defaults:
    # General settings
    - generic_pairwise

mode: 'pairwise'
max_steps: 15000
accumulate_grad_batches: 1
sim_loss: "mi"
lambda_sim: 0.0
lambda_seg: 1.0
lambda_mag: 0.00
lambda_grad: 0.5
lambda_inv: 100000000
learning_rate: 0.005
tensor_cores: false
batch_size: 1
checkpoint: ""
penalize: "v"
save_dir: 'pairwise'
load: ""


